plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  standard: config/base.yml

Rails/Output:
  Exclude:
    - "app/components/**/*"

# TODO: remove these files and fix offenses
Rails/I18nLocaleTexts:
  Exclude:
    - "app/mailers/passwords_mailer.rb"
    - "app/controllers/passwords_controller.rb"
    - "app/controllers/sessions_controller.rb"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  Exclude:
    - "bin/**/*"
    - "config/environments/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "tmp/**/*"
    - "vendor/**/*"
